
-- Create products table
CREATE TABLE purpleglass_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  description TEXT,
  features JSONB,
  image TEXT,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create orders table
CREATE TABLE purpleglass_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_info JSONB NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'pending',
  order_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create order_items table
CREATE TABLE purpleglass_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES purpleglass_orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES purpleglass_products(id),
  product_name TEXT NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL
);

-- Sample products data
INSERT INTO purpleglass_products (name, price, description, features, image, category)
VALUES
  (
    'Nebula Wireless Headphones',
    149.99,
    'Experience premium sound with our flagship Nebula wireless headphones. Featuring active noise cancellation, 40-hour battery life, and ultra-comfortable memory foam ear cushions.',
    '["Active Noise Cancellation", "40-hour battery life", "Memory foam ear cushions", "Touch controls", "Voice assistant compatible"]',
    '/products/headphones.png',
    'Audio'
  ),
  (
    'Astro Smart Watch',
    299.99,
    'The Astro Smart Watch combines elegant design with cutting-edge technology. Track your fitness, receive notifications, and monitor your health with this premium wearable device.',
    '["Heart rate monitoring", "Sleep tracking", "Water resistant (50m)", "7-day battery life", "GPS functionality"]',
    '/products/smartwatch.png',
    'Wearables'
  ),
  (
    'Quantum Portable Speaker',
    89.99,
    'Take your music anywhere with the Quantum Portable Speaker. Delivering powerful, immersive sound in a compact, waterproof design that fits in your bag.',
    '["Waterproof (IPX7 rated)", "12-hour battery life", "Built-in microphone", "Bluetooth 5.0", "Multi-speaker pairing"]',
    '/products/speaker.png',
    'Audio'
  ),
  (
    'Infinity Wireless Earbuds',
    129.99,
    'Infinity Wireless Earbuds offer crystal-clear sound, seamless connectivity, and a comfortable fit. Perfect for workouts, commuting, or all-day wear.',
    '["Active Noise Cancellation", "8-hour single charge", "Additional 24 hours with charging case", "Touch controls", "IPX5 sweat resistant"]',
    '/products/earbuds.png',
    'Audio'
  ),
  (
    'Pulse Gaming Headset',
    179.99,
    'Immerse yourself in the game with the Pulse Gaming Headset. Featuring 3D audio, customizable RGB lighting, and a detachable noise-cancelling microphone for clear team communication.',
    '["3D Spatial Audio", "Customizable RGB lighting", "Detachable noise-cancelling mic", "Memory foam ear cushions", "Multi-platform compatibility"]',
    '/products/headphones.png',
    'Gaming'
  ),
  (
    'Orbit Fitness Tracker',
    99.99,
    'Track your fitness journey with precision using the Orbit Fitness Tracker. Monitor heart rate, sleep patterns, and activity levels with this sleek, waterproof wearable.',
    '["24/7 heart rate monitoring", "Sleep quality analysis", "Waterproof to 50m", "Activity recognition", "7-day battery life"]',
    '/products/smartwatch.png',
    'Wearables'
  ),
  (
    'Echo Smart Home Hub',
    129.99,
    'Control your entire smart home ecosystem with the Echo Smart Home Hub. Connect and manage all your compatible devices from one sleek, intuitive interface.',
    '["Voice control", "Compatible with major smart home brands", "Energy usage monitoring", "Automated routines", "Enhanced security features"]',
    '/products/speaker.png',
    'Smart Home'
  ),
  (
    'Zenith Noise-Cancelling Earbuds',
    159.99,
    'Experience true audio isolation with Zenith Noise-Cancelling Earbuds. Featuring adaptive noise cancellation, premium sound quality, and a comfortable all-day fit.',
    '["Adaptive noise cancellation", "High-resolution audio", "Transparency mode", "10-hour battery life", "Wireless charging case"]',
    '/products/earbuds.png',
    'Audio'
  );
