
-- Create products table
CREATE TABLE purpleglass_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  description TEXT,
  features JSONB,
  image TEXT,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create orders table
CREATE TABLE purpleglass_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_info JSONB NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'pending',
  order_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create order_items table
CREATE TABLE purpleglass_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES purpleglass_orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES purpleglass_products(id),
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL
);

-- Sample products data
INSERT INTO purpleglass_products (name, price, description, features, image, category)
VALUES
  (
    'Nebula Wireless Headphones',
    149.99,
    'Experience premium sound with our flagship Nebula wireless headphones. Featuring active noise cancellation, 40-hour battery life, and ultra-comfortable memory foam ear cushions.',
    '["Active Noise Cancellation", "40-hour battery life", "Memory foam ear cushions", "Touch controls", "Voice assistant compatible"]',
    '/products/headphones.png',
    'Audio'
  ),
  (
    'Astro Smart Watch',
    299.99,
    'The Astro Smart Watch combines elegant design with cutting-edge technology. Track your fitness, receive notifications, and monitor your health with this premium wearable device.',
    '["Heart rate monitoring", "Sleep tracking", "Water resistant (50m)", "7-day battery life", "GPS functionality"]',
    '/products/smartwatch.png',
    'Wearables'
  ),
  (
    'Quantum Portable Speaker',
    89.99,
    'Take your music anywhere with the Quantum Portable Speaker. Delivering powerful, immersive sound in a compact, waterproof design that fits in your bag.',
    '["Waterproof (IPX7 rated)", "12-hour battery life", "Built-in microphone", "Bluetooth 5.0", "Multi-speaker pairing"]',
    '/products/speaker.png',
    'Audio'
  );
