
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fesxikwxswxnyqemhtfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlc3hpa3d4c3d4bnlxZW1odGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTM4ODYsImV4cCI6MjA1Nzg2OTg4Nn0.ZRCNn-tM24_YOO6rKaGv9Ujt_QY04wSg9G09vszNfLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the client and log the connection to help with debugging
console.log("Initializing Supabase client with URL:", SUPABASE_URL);
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a quick test to verify connectivity
(async () => {
  try {
    const { data, error } = await supabase.from('purpleglass_products').select('count');
    if (error) {
      console.error("Error connecting to Supabase:", error);
    } else {
      console.log("Successfully connected to Supabase. Products count:", data);
    }
  } catch (e) {
    console.error("Failed to test Supabase connection:", e);
  }
})();
